# Export reference values for the hexagon coordination sheaf.
#
# The Robotarium demo in the companion `robotarium_python_simulator` repository
# carries a NumPy port of `build_projection_escort_ring`, because the physical
# testbed runs plain Python. This script writes the numbers that let the port's
# test suite check itself against the real implementation.
#
# Usage:
#     julia --project=. docs/scripts/export_hexagon_golden.jl [output.json]
#
# Then copy the result to
#     rps/examples/sheaf_coordination/golden/hexagon_reference.json
# in the Robotarium checkout, where `test_hexagon_sheaf.py` picks it up.
#
# JSON is written by hand rather than through a package: the document is a
# dozen lines, and this keeps the script runnable from the plain package
# environment with no extra dependency.

using CellularSheaves
using LinearAlgebra

const N_AGENTS = 6
const RADIUS = 0.35
const TARGET_NODE = N_AGENTS + 1
const OBSERVERS = [1, 3, 5]
const TARGETS = [[0.0, 0.0], [0.4, -0.25], [-0.9, 0.6], [0.25, 0.4]]

fmt(x::Integer) = string(x)
fmt(x::Real) = string(round(Float64(x); digits=15))
fmt(v::AbstractVector) = "[" * join(fmt.(v), ", ") * "]"

function case_json(sheaf, target)
    x, null_basis = harmonic_extension(sheaf, Dict(TARGET_NODE => vcat(target, 1.0)))
    xv = Vector(x)
    rows = ["[" * join(fmt.(xv[3(i-1)+1:3(i-1)+2]), ", ") * "]" for i in 1:N_AGENTS]
    return """    {
      "target": $(fmt(target)),
      "nullity": $(size(null_basis, 2)),
      "q": [$(join(rows, ", "))]
    }"""
end

function main(path::AbstractString)
    sheaf = build_projection_escort_ring(N_AGENTS, TARGET_NODE, RADIUS; observers=OBSERVERS)
    cases = join([case_json(sheaf, t) for t in TARGETS], ",\n")

    open(path, "w") do io
        write(io, """{
  "_comment": "Generated by docs/scripts/export_hexagon_golden.jl from CellularSheaves.jl. Do not edit by hand.",
  "n_agents": $N_AGENTS,
  "radius": $(fmt(RADIUS)),
  "observers_one_based": $(fmt(OBSERVERS)),
  "observers_zero_based": $(fmt(OBSERVERS .- 1)),
  "cases": [
$cases
  ]
}
""")
    end
    println("wrote $path")
end

main(isempty(ARGS) ? joinpath(@__DIR__, "..", "..", "hexagon_reference.json") : ARGS[1])
